{% set version = "1.3.10" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-lifecontingencies
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/lifecontingencies_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/lifecontingencies/lifecontingencies_{{ version }}.tar.gz
  sha256: aa7a7431c724f569fc63a36783914cd9d9366b07393d8a7a110c5781f15873da
  patches:
    - patches/0001-expand-r-versions.patch

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rcpp >=1.0.0
    - r-markovchain
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rcpp >=1.0.0
    - r-markovchain

test:
  requires:
    - r-testthat
  commands:
    - $R -e "library('lifecontingencies')"                         # [not win]
    - $R -e "testthat::test_package('lifecontingencies')"          # [not win]
    - "\"%R%\" -e \"library('lifecontingencies')\""                # [win]
    - "\"%R%\" -e \"testthat::test_package('lifecontingencies')\"" # [win]

about:
  home: https://github.com/spedygiorgio/lifecontingencies
  license: MIT
  summary: "Classes and methods that allow the user to manage life table, actuarial tables (also multiple decrements tables). Moreover, functions to easily perform demographic, financial and actuarial mathematics on life contingencies insurances calculations are contained therein. See Spedicato (2013)\t<doi:10.18637/jss.v055.i10>."
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
