{% set version = "1.4.3" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-lifecontingencies
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/lifecontingencies_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/lifecontingencies/lifecontingencies_{{ version }}.tar.gz
  sha256: 4ae0aacf4e6a5d68dcec853ba48644741daadaa66700f069a37ff7896a51aa20
  patches:
    - patches/0001-expand-r-versions.patch

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rcpp >=1.0.0
    - r-markovchain
  run:
    - r-base
    - r-rcpp >=1.0.0
    - r-markovchain

test:
  requires:
    - r-testthat
  commands:
    - $R -e "library('lifecontingencies')"                          # [not win]
    - $R -e "testthat::test_package('lifecontingencies')"           # [not win]
    - "\"%R%\" -e \"library('lifecontingencies')\""                 # [win]
    - "\"%R%\" -e \"testthat::test_package('lifecontingencies')\""  # [win]

about:
  home: https://github.com/spedygiorgio/lifecontingencies
  license: MIT
  summary: "Classes and methods that allow the user to manage life table, actuarial tables (also multiple decrements tables). Moreover, functions to easily perform demographic, financial and actuarial mathematics on life contingencies insurances calculations are contained therein. See Spedicato (2013)\t<doi:10.18637/jss.v055.i10>."
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
